Added Contribution Guidelines and improve Readme
open-horizon/.github pull request #13
Opened 2022-03-04 20:49 UTC by Ayush7614

This PR Fix Issue No #11 

This PR Contains

* Added Contributing.md Files
* Added Contribution Guidelines
* Make Standard Readme
* Improve Readme

2022-03-04 21:11 UTC, Ayush7614 commented
cc @joewxboy

2022-03-04 21:25 UTC, joewxboy requested changes
Two comments:

1. We follow the [Linux Foundation Code of Conduct](https://lfprojects.org/policies/code-of-conduct/), so we should link directly to that.  Do you prefer to point to that inside your CODE_OF_CONDUCT.md file rather than posting the contents of the CoC, or just remove the markdown file entirely and just link directly to https://lfprojects.org/policies/code-of-conduct/

2. It looks like some of your hyperlinks are pointing to your personal repository at https://github.com/Ayush7614/

2022-03-05 04:14 UTC, Ayush7614 commented
cc @joewxboy

2022-03-05 18:24 UTC, joewxboy approved these changes

2022-03-05 18:24 UTC, merged