Updated Readme
open-horizon/.github pull request #17
Opened 2022-05-04 11:13 UTC by anurag8546

Added new features to Readme.md

2022-05-17 17:28 UTC, johnwalicki requested changes
Thanks for the contribution.  This looks great.  Can you make 2 changes before we merge this.

- Remove the unnecessary `<br>` lines from your commit.
- Remove one of the trailing newlines from your commit.

Thanks so much for joining the Open Horizon community.

2022-05-17 17:31 UTC, johnwalicki reviewed
@joewxboy   Are we moving the CODE_OF_CONDUCT.md or CONTRIBUTING.md for all of the repositories into this .github profile?

2022-05-17 17:38 UTC, johnwalicki commented
Some of the commits are messy multiple edits to links.  Maybe we could recommend to squash this into one commit ?

2022-06-14 14:28 UTC, johnwalicki commented
@anurag8546  It would be great to merge your contribution into the Open Horizon project. See above for some requested changes. Can you git squash these commits and sign the DCO?

2022-06-15 06:06 UTC, anurag8546 commented
@joewxboy  I've done both the required changes -
1) Removed unnecessary <br> from code
2) Removed  the trailing newline from the commit.

This still gives all checks have failed.

2022-06-15 06:07 UTC, anurag8546 commented
> @joewxboy I've done both the required changes -
> 
> 1. Removed unnecessary  from code
> 2. Removed  the trailing newline from the commit.
> 
> This still gives all checks have failed.

@johnwalicki

2022-06-15 15:46 UTC, joewxboy requested changes

2022-06-15 15:46 UTC, joewxboy commented on profile/README.md
> +<a href="https://twitter.com/lf_edge" alt="twitter"><img src="https://img.shields.io/badge/twitter-@lf_edge--twitter-yellow.svg" alt="twitter"></img></a>
Please remove closing `</img>` tag.  Image is not an HTML container, so it does not have a closing tag in HTML 4.x and HTML 5.

2022-06-15 15:49 UTC, joewxboy commented
@anurag8546 When you click on each individual commit, you are shown details about which checks are failing for that specific commit, and potentially how to resolve them.  Here's one:
https://github.com/open-horizon/.github/pull/17/checks

Let me know if the description on how to sign the commits is unclear or hard to follow.

2022-12-26 16:15 UTC, joewxboy commented
@anurag8546 Are you available to amend your commits to add a sign-off?  That will allow this PR to be merged.  Thanks.

2024-08-01 13:08 UTC, joewxboy approved these changes

2026-01-22 20:23 UTC, joewxboy commented
No DCO, closing

2026-01-22 20:23 UTC, closed without merging